### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by danielroe** [varletjs/varlet-nuxt#1]
This looks great!

A couple of suggestions.

1. It might be worth _always_ adding imports because this only disables the transform; even when `autoImports` is disabled users can still import manually from `#imports`:
   https://github.com/varletjs/varlet-nuxt/blob/f643334cfd263a7d7ddc3b288e43d433df6b7a22/src/module.ts#L17
1. It might be worth adding `transformPlugin.webpack` as well for those users who are using `@nuxt/webpack-builder`
1. What you have is perfect, but just FYI, we also h ave [`knitwork`](https://github.com/unjs/knitwork) for generating these imports:
   https://github.com/varletjs/varlet-nuxt/blob/f643334cfd263a7d7ddc3b288e43d433df6b7a22/src/gen.ts#L4-L19

**Comment by zhangmo8** [comment]
Thank you for your advice. I'll update my code in Future version

**Comment by zhangmo8** [comment]
1，2 is finished, [knitwork](https://github.com/unjs/knitwork) migration will be updated in the next few iterations
