### ISSUE TITLE
支持一下 nuxt layers

### ISSUE THREAD

**Issue by TurnerXi** [varletjs/varlet-nuxt#14]
![image](https://github.com/varletjs/varlet-nuxt/assets/25336287/d9d00cf4-19e4-4649-ba49-09d672f5775b)
模块在依赖的层中使用时process.cwd不能正确获取模块路径

![image](https://github.com/varletjs/varlet-nuxt/assets/25336287/5e2caee7-32c4-4689-96b0-d411480ba83d)
可以使用createResolver(import.meta.url).resolve获取varlet模块相对路径

**Comment by zhangmo8** [comment]
看起来不错，你愿意为这个特性提pr吗

**Comment by zhangmo8** [comment]
好吧，那我自己提交commit啦，已经更改完毕。十分感谢你的贡献和反馈 ！

**Comment by zhangmo8** [comment]
Hi @TurnerXi 可以提供一个最小的demo供我验证一下嘛，看起来你的项目是个monorepo
