### ISSUE TITLE
Please respect the achievements of others' labor

### ISSUE THREAD

**Issue by tolking** [varletjs/varlet-nuxt#4]
I found that the code of the `varlet-nuxt` was heavily plagiarized from [Vant nuxt](https://github.com/vant-ui/vant-nuxt). [commit](https://github.com/varletjs/varlet-nuxt/commit/c9b22b4ae1f02d4867afab95ff15cb8b5782aa2c)

The MIT License can only be used arbitrarily while retaining the original License. Otherwise, it would be considered plagiarism.

**Comment by zhangmo8** [comment]
I am sorry that this happened. I did draw lessons from some code from vant-nuxt and element-plus-nuxt in the process of writing. I am very grateful to the boss for their open-source spirit and learned a lot. I am sorry for the code is too similar. I will rectify it in the next few days. @tolking

**Comment by haoziqaq** [comment]
If you learn a repo, you can hang the inspiration from. I don't think it is necessary to deliberately modify the code

**Comment by tolking** [comment]
learn ?

Ctrl+c, Ctrl+v, then change the name. 

You city folks really know how to playing!

Please remove all code copied from [Vant nuxt](https://github.com/varletjs/varlet-nuxt/commit/c9b22b4ae1f02d4867afab95ff15cb8b5782aa2c)

**Comment by zhangmo8** [comment]
🤚Stop quarreling, I will rewrite a version, and thank you again for @tolking open source.

That's enough.
